In [9]:
import pandas as pd
import numpy as np

In [10]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [11]:
b=a.reshape(2,3)
print(b)

[[1 2 3]
 [4 5 6]]


In [12]:
arr = np.ones((5,5),dtype=int)
arr[1:4,1:4]=0
arr[2,2] = 9
print(arr)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [13]:
arr = np.arange(1,31).reshape(6,5)
print(arr[2:4,0:2])


[[11 12]
 [16 17]]


In [14]:
arr = np.arange(1,31).reshape(6,5)
print(arr[[0,1,2,3],[1,2,3,4]].reshape(1,4))

[[ 2  8 14 20]]


In [15]:
arr = np.arange(1,31).reshape(6,5)
print(arr[[0,4,5],3:5])

[[ 4  5]
 [24 25]
 [29 30]]


## tasks

In [3]:
##S1
import numpy as np

# 1. Install NumPy in your Python environment using pip, then create a Python file called insta_likes.py and import numpy as np at the top.
# 2.
# Create a NumPy array called followers using np.array() that stores the follower counts for 5 Instagram influencers: [1200, 15000, 67000, 340000, 1250000]. Print the array, its shape, number of dimensions, and data type.
# 3.
# Use np.arange() to generate an array of order IDs for 10 consecutive Zomato orders starting from 101. Print the array and its size.
# 4.
# Create a 3x3 NumPy array using np.eye() to represent a 'like' identity matrix for a new Spotify playlist feature. Print the matrix and explain what the diagonal values represent in a comment.
# 5.
# Convert a Python list of cricket scores [45, 67, 120, 89, 54] to a NumPy array, then use the .itemsize attribute to print how many bytes each score takes in memory.<br><br><em><strong>Hint:</strong> Use np.array() for conversion and .itemsize for memory size.</em>


influencer=np.array([1200,15000,67000.340000,1250000],dtype="int64")
print(influencer)
print(influencer.shape)
print(influencer.ndim)
print(influencer.dtype)

zomato=np.arange(101,111)
print(zomato, zomato.size)

spotify=np.eye(3)
print(spotify)

cricket_scores=np.array([45,67,120,89,540],dtype="int64")
print(cricket_scores, cricket_scores.itemsize)

[   1200   15000   67000 1250000]
(4,)
1
int64
[101 102 103 104 105 106 107 108 109 110] 10
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 45  67 120  89 540] 8


In [5]:
##S2
1.
Create a 2D NumPy array representing the ratings (out of 5) given by 4 users to 5 different food items on Zomato. Use slicing to extract the ratings given by the second and third users only.
2.
Given a NumPy array of daily steps tracked for 10 days, use boolean indexing to select only the days where the steps were greater than 8000.<br><br><em><strong>Hint:</strong> Use an array like steps = np.array([7500, 8200, 9000, ...]) and apply a boolean condition.</em>
3.
Create a NumPy array of IPL team scores for 8 matches. Use fancy indexing to select the scores from matches 2, 5, and 7, and print them.
4.
Suppose you have a NumPy array of product prices from Flipkart. Use broadcasting to apply a 10% discount to all prices and print the new array.<br><br><em><strong>Constraint:</strong> Do not use any loops.</em>
5.
Given a NumPy array of user ratings (can be negative, zero, or positive) for songs on Spotify, use boolean masking to set all negative ratings to zero, keeping other ratings unchanged.
"""
import numpy as np
ratings = np.array([
    [5, 4, 3, 4, 5],   # User 1
    [3, 2, 4, 3, 4],   # User 2
    [4, 5, 5, 4, 5],   # User 3
    [2, 3, 3, 2, 3]    # User 4
])
print(ratings[1:3])

steps = np.array([7500, 8200, 9000, 6700, 10000, 7800, 8500, 9200, 7000, 8800])
print(steps>8000)

ipl_score=np.array([100,150,51,200,190,145,138,185,153,100])
print(ipl_score[[2,5,7]])

flipcart_price=np.array([100,5200,150,5820,415,451,4812,452])
discount_price=flipcart_price * 0.9
print(discount_price)

spotify_ratings=np.array([-2,-1,-3,0,0,5,3,4,2])
spotify_ratings[spotify_ratings<0]=0
print(spotify_ratings)

SyntaxError: invalid decimal literal (4109639357.py, line 3)

# Assistant
The error occurs because you have numbered list items (like `1.`, `2.`, etc.) directly in your Python code, which Python interprets as invalid decimal literals.

**Explanation:**
Python sees `1.` as the start of a decimal number, but when it's followed by text instead of digits, it creates a syntax error. The numbered list items in your code are causing this issue.

Would you like me to provide the corrected code?

# User
yes

In [6]:
# Assistant
# S2 - NumPy Array Operations

# 1. Create a 2D NumPy array representing the ratings (out of 5) given by 4 users to 5 different food items on Zomato. 
# Use slicing to extract the ratings given by the second and third users only.
import numpy as np
ratings = np.array([
    [5, 4, 3, 4, 5],   # User 1
    [3, 2, 4, 3, 4],   # User 2
    [4, 5, 5, 4, 5],   # User 3
    [2, 3, 3, 2, 3]    # User 4
])
print("Ratings from second and third users:")
print(ratings[1:3])

# 2. Given a NumPy array of daily steps tracked for 10 days, use boolean indexing to select only the days 
# where the steps were greater than 8000.
steps = np.array([7500, 8200, 9000, 6700, 10000, 7800, 8500, 9200, 7000, 8800])
print("\nDays with steps > 8000:")
print(steps[steps > 8000])  # Fixed: Added boolean indexing to actually filter the values

# 3. Create a NumPy array of IPL team scores for 8 matches. Use fancy indexing to select the scores 
# from matches 2, 5, and 7, and print them.
ipl_score = np.array([100, 150, 51, 200, 190, 145, 138, 185])  # Fixed: Made it 8 matches as specified
print("\nScores from matches 2, 5, and 7 (0-indexed as 1, 4, 6):")
print(ipl_score[[1, 4, 6]])  # Fixed: Adjusted indices for matches 2, 5, 7 (0-indexed)

# 4. Suppose you have a NumPy array of product prices from Flipkart. Use broadcasting to apply a 10% discount 
# to all prices and print the new array.
flipkart_price = np.array([100, 5200, 150, 5820, 415, 451, 4812, 452])  # Fixed: Corrected variable name
discount_price = flipkart_price * 0.9
print("\nPrices after 10% discount:")
print(discount_price)

# 5. Given a NumPy array of user ratings (can be negative, zero, or positive) for songs on Spotify, 
# use boolean masking to set all negative ratings to zero, keeping other ratings unchanged.
spotify_ratings = np.array([-2, -1, -3, 0, 0, 5, 3, 4, 2])
spotify_ratings[spotify_ratings < 0] = 0
print("\nSpotify ratings after setting negative values to zero:")
print(spotify_ratings)

Ratings from second and third users:
[[3 2 4 3 4]
 [4 5 5 4 5]]

Days with steps > 8000:
[ 8200  9000 10000  8500  9200  8800]

Scores from matches 2, 5, and 7 (0-indexed as 1, 4, 6):
[150 190 138]

Prices after 10% discount:
[  90.  4680.   135.  5238.   373.5  405.9 4330.8  406.8]

Spotify ratings after setting negative values to zero:
[0 0 0 0 0 5 3 4 2]



**Key fixes made:**
1. **Removed numbered list items** - Converted them to comments to avoid syntax errors
2. **Added proper boolean indexing** - Changed `steps>8000` to `steps[steps > 8000]` to actually filter values
3. **Fixed array size** - Made IPL scores array have 8 elements as specified
4. **Corrected variable name** - Changed `flipcart_price` to `flipkart_price` for consistency
5. **Added descriptive print statements** - Made output clearer for each operation

In [7]:
##s3
"""
1.
Create two NumPy arrays representing the daily step counts of two friends over a week and use element-wise addition, subtraction, multiplication, and division to compare their activity levels.
2.
Simulate a Spotify-like 'Recommended Songs' feature: Given two 3x3 matrices representing user-song interaction scores (user preferences and song popularity), use dot() and matmul() to compute the final recommendation matrix and explain the difference between the two results.
3.
Given a 4x4 NumPy matrix representing the pixel brightness of a small Instagram image, use transpose (T) to rotate the image and then calculate the mean, median, standard deviation, and variance of the pixel values.
4.
Take a 3x3 NumPy matrix representing a Zomato restaurant rating correlation grid and use np.linalg.inv(), np.linalg.det(), and np.linalg.eig() to compute its inverse, determinant, and eigenvalues/eigenvectors.<br><br><em><strong>Hint:</strong> If the matrix is not invertible, modify one value and try again.</em>
5.
Create a NumPy array of shape (2, 6) representing the number of orders placed on Swiggy in two cities over 6 days. Reshape it to (3, 4), flatten it, split it into two equal parts, and then stack both parts vertically.
"""

import numpy as np

"""
first_friend=np.array([5000,6000,5000,5500,6400,7800,9000],dtype="int64")
second_friend=np.array([5600,4500,7800,9800,4500,6000,10000],dtype="int64")

print(first_friend+second_friend)
print(first_friend-second_friend)
print(first_friend*second_friend)
print(first_friend/second_friend)


# User preferences matrix (3 users × 3 song features)
user_preferences = np.array([
    [5, 3, 1],
    [4, 2, 3],
    [1, 5, 4]
])

# Song popularity matrix (3 song features × 3 songs)
song_popularity = np.array([
    [2, 4, 1],
    [3, 1, 5],
    [4, 2, 3]
])

recommendation_dot = np.dot(user_preferences, song_popularity)

recommendation_matmul = np.matmul(user_preferences, song_popularity)

print("Recommendation Matrix using dot():")
print(recommendation_dot)

print("\nRecommendation Matrix using matmul():")
print(recommendation_matmul)

image = np.array([
    [120, 150, 180, 200],
    [100, 130, 170, 210],
    [90,  140, 160, 220],
    [80,  110, 190, 230]
])
rotated_image=image.T
print(rotated_image)
mean=np.mean(image)
median=np.median(image)
std_dev=np.std(image)
variance=np.var(image)

print("\nMean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)
"""

orders = np.array([
    [120, 135, 150, 145, 160, 170],  # City 1
    [100, 110, 125, 130, 140, 155]   # City 2
])
print("Original Array (2x6):")
print(orders)

#Reshape(3,4)
reshaped=orders.reshape(3,4)
print(reshaped)


flatten=orders.flatten()
print(flatten)

part1,part2=np.split(flatten,2)
print(part1,part2)



#Vertical Stack
stacked=np.vstack((part1,part2))
print(stacked)


# import pandas as pd
# from scipy.stats import zscore
# df = pd.DataFrame({
#     'days' :[1,2,3,4,5,6,7,8,9,10,11], 
#     "sales" :[100,200,250,350,170,300,400,500,600,-10000,20000]
# })

# # print(df)
# df['z_score'] = zscore(df['sales'])
# print(df)
# outlier = df[df['z_score'].abs() > 1]
# print(outlier)

Original Array (2x6):
[[120 135 150 145 160 170]
 [100 110 125 130 140 155]]
[[120 135 150 145]
 [160 170 100 110]
 [125 130 140 155]]
[120 135 150 145 160 170 100 110 125 130 140 155]
[120 135 150 145 160 170] [100 110 125 130 140 155]
[[120 135 150 145 160 170]
 [100 110 125 130 140 155]]


In [8]:
##s4
"""
1.
Download a sample CSV file of IPL cricket match scores from Kaggle or any public dataset, and use pd.read_csv() to load it into a DataFrame. Print the first 5 rows to verify the data.
2.
Find a small JSON dataset of trending songs (for example, from Spotify's API samples or any open JSON file), and use pd.read_json() to import it into a DataFrame. Display the DataFrame's column names and data types using df.info().
3.
You have a TSV (tab-separated values) file containing Zomato restaurant data. Use pd.read_csv() with the correct separator to load the data, and then use df.describe(include='all') to generate summary statistics.<br><br><em><strong>Hint:</strong> The separator for TSV files is '//t'.</em>
4.
Download a large Excel file (at least 10,000 rows) of Flipkart product listings. Use pd.read_excel() with the chunksize parameter to read the file in chunks of 2000 rows, and print the number of rows in each chunk as you iterate.
5.
Use ChatGPT or Copilot to generate a Python code snippet that reads a semicolon-separated CSV of Paytm transactions, detects missing values, and prints out which columns have nulls. Test the code with a small sample file and fix any errors you encounter.
"""

import pandas as pd
# df=pd.read_csv('LIBRARY/ASSIGNMENTS/pandas/IPL.csv')
# print(df.head())
# print(df.info())

# df=pd.read_csv("LIBRARY\ASSIGNMENTS\pandas\sample.tsv",sep="\t")
# print(df.describe(include="all"))


# df=pd.read_csv('LIBRARY/ASSIGNMENTS/pandas/IPL.csv',chunksize=2000)
# for chunk in df:
#     print(chunk)


"""
df=pd.read_csv("LIBRARY\ASSIGNMENTS\pandas\paytm.csv",sep=";")
print(df)

# Check for missing values
print("\nMissing Values Count:")
print(df.isnull().sum())

# Print columns having null values
null_columns = df.columns[df.isnull().any()]

print("\nColumns with Null Values:")
for col in null_columns:
    print(col)
"""

'\ndf=pd.read_csv("LIBRARY\\ASSIGNMENTS\\pandas\\paytm.csv",sep=";")\nprint(df)\n\n# Check for missing values\nprint("\nMissing Values Count:")\nprint(df.isnull().sum())\n\n# Print columns having null values\nnull_columns = df.columns[df.isnull().any()]\n\nprint("\nColumns with Null Values:")\nfor col in null_columns:\n    print(col)\n'

In [10]:

# s5
# 1. Connect to a MySQL or PostgreSQL database using SQLAlchemy and pandas, then use pd.read_sql() to load the entire 'restaurants' table (imagine Zomato backend) into a DataFrame and display the first 5 rows.
# 2. Use pd.read_sql_query() to fetch only the 'name' and 'rating' columns from a 'movies' table (think BookMyShow-like data) where rating is above 8, and print the resulting DataFrame.
# Hint: Write a custom SQL SELECT query as the first argument to pd.read_sql_query().
# 3. Read a JSON dataset from the URL https://jsonplaceholder.typicode.com/users using pandas, convert it into a DataFrame, and print the usernames column.
# Hint: Use pd.read_json() directly with the URL.
# 4. You have two CSV files: 'orders.csv' (order_id, user_id, amount) and 'users.csv' (user_id, username). Load both into DataFrames using pathlib for file paths, then merge them on 'user_id' to show a combined table with username and amount.
# 5. Concatenate two DataFrames representing 'today_orders' and 'yesterday_orders' (each with columns: order_id, item, price), and display the combined DataFrame.
# Constraint: Use pd.concat() and reset the index after concatenation.

import pandas as pd

# Reading JSON data from URL and displaying usernames
df = pd.read_json("https://jsonplaceholder.typicode.com/users")
print(df['username'])

0                Bret
1           Antonette
2            Samantha
3            Karianne
4              Kamren
5    Leopoldo_Corkery
6        Elwyn.Skiles
7       Maxime_Nienow
8            Delphine
9      Moriah.Stanton
Name: username, dtype: object


In [11]:
##s6
"""
1.
Download a sample CSV file of IPL player stats (include columns like player name, runs, matches, and some missing values). Load it into a pandas DataFrame and use isnull() and notnull() to print how many missing values are present in each column.
2.
Using the loaded IPL player stats DataFrame, apply dropna(axis=0, how='any') to remove all rows with any missing data and display the shape of the DataFrame before and after dropping.
3.
For the 'runs' column in your IPL player stats DataFrame, use fillna() to replace missing values with the mean of the column. Print the updated column to verify the changes.
4.
Simulate a Zomato-style restaurant ratings dataset with some missing ratings. Use forward fill (method='ffill') to fill missing values in the ratings column, then use backward fill (method='bfill') for any remaining missing values. Show the before and after results.
5.
Pick any one column with missing values from your dataset and explain which missingness mechanism (MCAR, MAR, or MNAR) is most likely and why, using 2-3 sentences.<br><br><em><strong>Hint:</strong> Think about whether the missing data is random or related to other factors in the dataset.</em>
"""
import pandas as pd
import numpy as np
"""df = pd.read_csv("LIBRARY\\ASSIGNMENTS\\pandas\\IPL.csv")
# Missing values count for each column
missing_count = df.isnull().sum()

# Columns with null values
null_columns = missing_count[missing_count > 0]
print("\nColumns with Null Values:")
print(null_columns)

# Total missing values in the entire dataset
total_missing = df.isnull().sum().sum()
print("\nTotal Missing Values:", total_missing)


df = pd.read_csv("LIBRARY\\ASSIGNMENTS\\pandas\\IPL.csv")
original_rows = len(df)

df = df.dropna(axis=0)

new_rows = len(df)

print("Rows removed:", original_rows - new_rows)
print("Remaining rows:", new_rows)

df = pd.DataFrame({
    "Restaurant": [
        "Spice Villa",
        "Food Hub",
        "Pizza Point",
        "Royal Dine",
        "Burger Town",
        "Cafe Delight"
    ],
    "Rating": [np.nan, 4.2, 3.8, np.nan, np.nan, 4.5]
})

print("Before Filling:")
print(df)

print("Forward filling")
df['Rating']=df['Rating'].ffill()
print(df)

print("Backword Filling")
df["Rating"]=df["Rating"].bfill()
print(df)

"""

'df = pd.read_csv("LIBRARY\\ASSIGNMENTS\\pandas\\IPL.csv")\n# Missing values count for each column\nmissing_count = df.isnull().sum()\n\n# Columns with null values\nnull_columns = missing_count[missing_count > 0]\nprint("\nColumns with Null Values:")\nprint(null_columns)\n\n# Total missing values in the entire dataset\ntotal_missing = df.isnull().sum().sum()\nprint("\nTotal Missing Values:", total_missing)\n\n\ndf = pd.read_csv("LIBRARY\\ASSIGNMENTS\\pandas\\IPL.csv")\noriginal_rows = len(df)\n\ndf = df.dropna(axis=0)\n\nnew_rows = len(df)\n\nprint("Rows removed:", original_rows - new_rows)\nprint("Remaining rows:", new_rows)\n\ndf = pd.DataFrame({\n    "Restaurant": [\n        "Spice Villa",\n        "Food Hub",\n        "Pizza Point",\n        "Royal Dine",\n        "Burger Town",\n        "Cafe Delight"\n    ],\n    "Rating": [np.nan, 4.2, 3.8, np.nan, np.nan, 4.5]\n})\n\nprint("Before Filling:")\nprint(df)\n\nprint("Forward filling")\ndf[\'Rating\']=df[\'Rating\'].ffill()\nprint(df

In [12]:
##s7
""""
Tasks
1.
Given a CSV file containing Zomato restaurant ratings, use pandas to detect outliers in the 'user_rating' column using the IQR method and print the indices of the detected outliers.a
2.
Create a boxplot for the 'order_amount' column from a Swiggy orders dataset using matplotlib, and visually identify any outliers present.<br><br><em><strong>Hint:</strong> Use plt.boxplot() and label your axes for clarity.</em>
3.
Apply winsorization to the 'transaction_amount' column in a Paytm transactions DataFrame to cap all values above the 95th percentile and below the 5th percentile, then display the updated column statistics.
4.
You have a DataFrame of Flipkart product prices stored as strings with currency symbols (e.g., '₹1,299'). Convert this column to numeric type using pandas, ensuring all non-numeric characters are removed.<br><br><em><strong>Hint:</strong> Use str.replace() and astype().</em>
5.
Fix the following code snippet where the 'is_premium' column in a Spotify user DataFrame is a mix of boolean, string, and integer types. Convert the entire column to boolean type, treating 'True', 1, and 'yes' as True, and everything else as False.
"""

import pandas as pd
import matplotlib.pyplot as plt
"""df=pd.read_csv("LIBRARY\\ASSIGNMENTS\\pandas\\zomato.csv")
Q1=df['user_rating'].quantile(0.25)
Q3=df['user_rating'].quantile(0.75)

IQR=Q3-Q1

lower_bound=Q1 - 1.5*IQR
upper_bound=Q3+ 1.5*IQR

outliers=df[
    (df['user_rating'] < lower_bound) |
    (df['user_rating'] > upper_bound)
]
print(outliers.index+1)

plt.boxplot(df['user_rating'])
plt.ylabel("Ratings")
plt.title("Ratings")
plt.show()"""

df =pd.DataFrame({
    "id" :[1,2,3,4,5,6,7],
    "name" :["ram","sita","ravan","laxman","surekha","ravi","ramesh"],
    "status" :["True","False","True","False","True","False","True"],
    "experience":["2","4","1","5","7","9","3"],
    "city" :["ahm","ahmedabad","bombay","mumbai","delhi","pune","rajstan"]
})

df["city"]=df["city"].replace(["ahm","bombay"],["ahmedabad","mumbai"])
print(df)

   id     name status experience       city
0   1      ram   True          2  ahmedabad
1   2     sita  False          4  ahmedabad
2   3    ravan   True          1     mumbai
3   4   laxman  False          5     mumbai
4   5  surekha   True          7      delhi
5   6     ravi  False          9       pune
6   7   ramesh   True          3    rajstan
